<?php include "inc/header.php" ?>
<?php include "day-message.php" ?>
<?php include "array-type.php" ?>
<?php include "bce.php" ?>
<?php include "chemistry.php" ?>
<?php include "math.php" ?>
<?php include "ntf.php" ?>
<?php include "physics.php" ?>
<?php include "counter.php" ?>
<?php include "syllabus.php" ?>
<?php include "routine.php" ?>
<?php include "bus-route.php" ?>
<?php include "inc/footer.php"  ?>